### ISSUE TITLE
Report the bug!

### ISSUE THREAD

**Issue by Jammly** [SublimeText/Vue#45] opened 2024-12-12 06:52 UTC
![image](https://github.com/user-attachments/assets/e98250d5-4d83-4f1b-a07b-4700f43fcb8f)
![image](https://github.com/user-attachments/assets/e4159cd5-d88c-4078-90a5-bfe1249d539d)

update to latest version v5.0.1，a error occurs！

**Comment by deathaxe** [comment] 2024-12-12 17:01
Duplicate of #44

**Closed by deathaxe** 2024-12-12 17:01 UTC

**Comment by ChuksFestus** [comment] 2025-01-13 22:53
This isn't fixed yet. Its not a duplicate of #43, or #44. I don't have any of these installed or any 3rd party syntax highlighter thats js related.
- [JavaScriptNext - ES6 Syntax](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax)
- [TypeScript](https://packagecontrol.io/packages/TypeScript)
- [TypeScript Syntax](https://packagecontrol.io/packages/TypeScript%20Syntax)

theres probably something up with the latest upate.

**Comment by ChuksFestus** [comment] 2025-01-13 23:45
Update on this. So I notice when I use the code from [4107-4.1.0](https://github.com/SublimeText/Vue/releases/tag/4107-4.1.0) Vue Component.sublime-syntaxt, the syntaxt highlight works perfectly.

**Comment by deathaxe** [comment] 2025-01-14 07:39
The required context `#expression` is certainly part of JavaScript syntax shipped with current releases of ST4 and has been around for quite a while. If you see this error you most likely have an out-dated overridden JavaScript syntax sitting around somewhere.

You can check _Packages_ folder and remove a possibly existing _JavaScript_ folder, which would override ST's default JavaScript package. Maybe you also have an override in _Installed Packages/_

That's not an issue with this package!

**Comment by ChuksFestus** [comment] 2025-01-14 14:12
Seems like the issue was from [naomi](https://packagecontrol.io/packages/Naomi). Thanks.

**Comment by tonylegrone** [comment] 2025-04-24 16:04
For me, it turned out the the "Better Javascript" package force disables the default sublime javascript package. I had to remove better javascript and re-enable javascript.
