### ISSUE TITLE
Syntax don't want to load

### ISSUE THREAD

**Issue by SynCap** [SublimeText/Vue#44] opened 2024-12-11 14:25 UTC
```
error: Error loading syntax file "Packages/Vue/Vue Component.sublime-syntax": Packages/Vue/Vue Component.sublime-syntax: no such target scope:source.js#expression
```

Package version: 5.0.1
Sublime version: 4180

**Comment by deathaxe** [comment] 2024-12-11 16:50
Possible duplicate of #43.

Vue is based on and designed to primarily work with ST's default syntaxes. The error log indicates an incompatible or out-dated JavaScript being installed, overriding default `source.js` scope.

Uninstalling them fixes the issue.

see: https://github.com/SublimeText/Vue?tab=readme-ov-file#2-scripts-are-not-correctly-highlighted

**Closed** 2024-12-11 16:51 UTC
Labels: question
